### ISSUE TITLE
Mejorar exportación de módulos

### ISSUE THREAD

**Issue by efulet** [reigncl/reign-utils#13]
Se propone realizar una mejora en la exportación de los módulos

**Comment by JonDotsoy** [comment]
Con @framled conversamos de dividir los modules en submodules dentro de un una carpeta `packages`. la idea es tener un modulo por cada sub carpeta.

**Ejemplos:**
- logger `packages/logger` `npm i @reignmodule/logger`
- listeningListener `packages/listeningListener ` `npm i @reignmodule/listeningListener`

Luego cada subcarpeta tiene su propio `package.json` con la referencia al modulo en https://www.npmjs.com.
